name: Build Gentoo Stage4

on:
  push:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  pull_request:
    paths-ignore:
      - '**.md'
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.flavour }} (${{ matrix.arch }})
    strategy:
      matrix:
        arch: [amd64]
        flavour: [containeros, sway]
    uses: bbusse/github-workflows/.github/workflows/build-gentoo-stage4.yml@dev
    with:
      arch: ${{ matrix.arch }}
      flavour: ${{ matrix.flavour }}
      image_name: gentoo-stage4
      registry: ghcr.io/bbusse
      tag: latest
    secrets:
      GHCR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
